### ISSUE TITLE
Failing on Yosemite!

### ISSUE THREAD

**Issue by swillis** [jcf/dotfiles#30]
Hey!

So I guess I may have gotten used to your dotfiles over the years, but now I can't get them set up on my machine :(

![screenshot 2014-10-21 20 19 53](https://cloud.githubusercontent.com/assets/1385001/4725242/e25afce8-5957-11e4-985b-a12637fa532d.png)

I tried installing PhantomJS independently but it doesn't currently support Yosemite. Although I am not sure if that is actually what is causing it to fail. Any ideas?

Thanks!

**Comment by jcf** [comment]
Hi @swillis,

Just spotted this issue. I might need to tweak my GitHub notification settings… Sorry about that!

Maybe you've started your own dotfiles repo since we last spoke and this is no longer a problem? If you're still using a fork of my dotfiles try installing phantomjs yourself with `brew install phantomjs` and see what happens.

**Comment by swillis** [comment]
Hey @jcf! Thanks for getting back to me :D 

In the end I decided to start from scratch with my dotfiles so that I could gain a working knowledge of what everything actually does. And so far it is all working very nicely, except for one thing.

With your dotfiles, I used to be able to use the alias "c" and write "c MY_PROJECT" and it would cd into my Code folder and also into the project folder. I have many, many aliases now (they are my friends) but I CANNOT figure this one out for some reason! Do you know what I am missing? Am I being dumb??

All the best,

Sam

**Comment by jcf** [comment]
Ahh, yes! That's a nice feature of ZSH that I've not been able to replicate in other shells to date.

It's implemented as a [function][], with explicit [completion][] in [jcf/prezto][]. To replicate it in your own dotfiles you'll need to find a directory where ZSH is looking for functions (checkout [`$fpath`]) and add a `c` file and an `_c` file.

So, say your `$fpath` includes `/Users/sam/.dotfiles/functions` you'd want to create `/Users/sam/.dotfiles/functions/c` with this in it:

``` sh
cd ~/Code/$1;
```

And to define how you want to complete that function, create `/Users/sam/.dotfiles/functions/_c` with this in it:

``` sh
#compdef c
_files -W ~/Code -/
```

HTH.

[function]: https://github.com/jcf/prezto/blob/a220cd7cb0e0551831c870004c77454828df429e/modules/utility/functions/c
[completion]: https://github.com/jcf/prezto/blob/a220cd7cb0e0551831c870004c77454828df429e/modules/utility/functions/_c
[`$fpath`]: http://unix.stackexchange.com/questions/33255/how-to-define-and-load-your-own-shell-function-in-zsh
[jcf/prezto]: https://github.com/jcf/prezto/tree/a220cd7cb0e0551831c870004c77454828df429e/modules/utility/functions

**Comment by swillis** [comment]
Awesome! I will try and get that set up this weekend. The missing piece of my dev setup :D




Thanks a lot James!




Sam


—
